# Generated by Django 3.2.9 on 2022-11-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=3000)),
            ],
        ),
    ]
